---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "edge-v1"
  namespace: "default"
  labels:
    app: "edge-v1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "edge-v1"
  template:
    metadata:
      labels:
        app: "edge-v1"
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcloud-key
      containers:
      - name: "github-dpclab-censorscout-back"
        image: "gcr.io/dpclab-215801/github-dpclab-censorscout-back:7924b1e782e0ce528fd2cf3533f1a0df1d421a0f"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: NODE_ENV
          value: production
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "edge-v1-hpa"
  namespace: "default"
  labels:
    app: "edge-v1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "edge-v1"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80